title: Minimal theme
logo: /assets/img/1720287412867.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

github:
  repository_url: https://github.com/giovannicintra/repo
  zip_url: https://github.com/giovannicintra/repo/zipball/main
  tar_url: https://github.com/giovannicintra/repo/tarball/main
